### ISSUE TITLE
Operating Humidity on rak3172

### ISSUE THREAD

**Issue by ImanIDG** [RAKWireless/rakwireless-docs#103]
Hi there, I'm currently working on rak3172 in a little humid condition. I was wondering what is the "Operating Humidity" for rak3172 and rak3172-t?
Thanks in advance.

**Comment by kneelyrac** [comment]
Hello @ImanIDG,
Apologies for the very, very late response, but I want you to know that this issue has already been raised to the R&D team. I'll be closing this issue and refer to the forum instead: https://forum.rakwireless.com/

Thank you!
