### ISSUE TITLE
How to connect the rak3172 to the computer 

### ISSUE THREAD

**Issue by dodo124** [RAKWireless/rakwireless-docs#104]
Hi, I do have the Rak3172 development board and I'm using the example code for the board as well as the code for the gyro https://docs.rakwireless.com/Product-Categories/WisBlock/RAK12034/Quickstart/.
My problem is that I failed to get a timer interrupt working.
The Timer1 library is not working because it's a arduino library. So I thought to use bare metal programming using the cube IDE. Therefore I need to upload the code.

But how am I supposed to connect it to the board?

Or is there any timer based interrupt already implemented in Rui3?

Kind regards Dominik

**Comment by beegee-tokyo** [comment]
[RUI3 Timer](https://docs.rakwireless.com/RUI3/System/#timer)

**Comment by dodo124** [comment]
Thank you :-)
