### ISSUE TITLE
URL for adafruit-nrfutil.exe leads to file Windows Defender identifies as a Trojan

### ISSUE THREAD

**Issue by logikal** [RAKWireless/rakwireless-docs#112]
~The link that's currently in the docs to link to the `adafruit-nrfutil.exe` tool is is malformed, and includes a url-encoded `$(APPVEYOR_REPO_TAG_NAME)` reference that shouldn't be there.~

I see now that the URL isn't malformed, https://github.com/adafruit/Adafruit_nRF52_nrfutil/tree/%24(APPVEYOR_REPO_TAG_NAME is an actual tag in the adafruit repo. 

https://github.com/RAKWireless/rakwireless-docs/blob/6c93776ac2826e52d1202d6938386ed5daed93bd/docs/Product-Categories/WisBlock/RAK4631/Quickstart/README.md?plain=1#L543

When I tried to download this today, Windows Defender blocked the download, saying that the exe contained a Trojan.
![Screenshot 2024-08-21 145030](https://github.com/user-attachments/assets/67d321a5-ccbf-4902-be9e-e51cd645d1b6)

Windows Defender doesn't find a trojan in the exe that's inside a release 
 (e.g. https://github.com/adafruit/Adafruit_nRF52_nrfutil/releases/tag/0.5.3.post17) zip from the adafruit repo itself.

Even if this is a false positive, it is probably better to grab the release from the adafruit repo: to get the most recent version and to prevent people from downloading the version that is flagged, correct or not, as a trojan.

**Comment by kneelyrac** [comment]
Hi @logikal,
The guide has been updated. Thank you for flagging this.
I'll be closing this issue now.
