### ISSUE TITLE
Missing Figure

### ISSUE THREAD

**Issue by SoothingMist** [RAKWireless/rakwireless-docs#113]
At the top of README text, this figure is missing: [RAK-only-gray](https://github.com/RAKWireless/rakwireless-docs-internal/blob/drafts/docs/.vuepress/public/assets/rakwireless/RAK-only-gray.png)

**Comment by kneelyrac** [comment]
Hi @SoothingMist 
Checked the README text, and the logo is visible on my end. Kindly check again and let me know if it's still recurring on your end. 

![2024-08-30 03_38_28-RAKWireless_rakwireless-docs_ Open-source documentation center of RAKwireless  T](https://github.com/user-attachments/assets/6e4cd861-28c6-4e13-a1d1-0041125196c6)

Thank you!

**Comment by SoothingMist** [comment]
When I click on that link from Chrome I get a "dead-link" page.

---------- Original Message ----------

**Comment by kneelyrac** [comment]
Hi @SoothingMist 
I checked with my colleagues, and everything was fine on their end as well.
Kindly clear your browser cache and the check again.
Also, I'll be closing this ticket now. Thank you so much!
