### ISSUE TITLE
Incorrect Arduino IDE version

### ISSUE THREAD

**Issue by SoothingMist** [RAKWireless/rakwireless-docs#115]
At [rakwireless-docs](https://github.com/RAKWireless/rakwireless-docs/tree/master)/[docs](https://github.com/RAKWireless/rakwireless-docs/tree/master/docs)/[Knowledge-Hub](https://github.com/RAKWireless/rakwireless-docs/tree/master/docs/Knowledge-Hub)/[Learn](https://github.com/RAKWireless/rakwireless-docs/tree/master/docs/Knowledge-Hub/Learn)/[Installation-of-Board-Support-Package-in-Arduino-IDE](https://github.com/RAKWireless/rakwireless-docs/tree/master/docs/Knowledge-Hub/Learn/Installation-of-Board-Support-Package-in-Arduino-IDE)

The latest Arduino IDE is misstated. It is beyond v2 now. Other changes may be necessary since the IDE interface has changed.

**Comment by kneelyrac** [comment]
Hi @SoothingMist 

Apologies for the inconvenience. 
We are currently unable to update the website, as we are in the process of updating and migrating our documents to provide an accurate and up-to-date documentation site.

Thank you!
