### ISSUE TITLE
Missing Figures

### ISSUE THREAD

**Issue by SoothingMist** [RAKWireless/rakwireless-docs#116]
At https://github.com/RAKWireless/rakwireless-docs/tree/master/docs/Product-Categories/WisBlock/RAK1901/Quickstart, the figures all seem to be missing. Using Google Chrome to view.

**Comment by kneelyrac** [comment]
Hi @SoothingMist, 

Checked the [site](https://docs.rakwireless.com/Product-Categories/WisBlock/RAK1901/Quickstart/) with 3 machines and all images are visible. 

Please check again. Thank you!
