### ISSUE TITLE
Suggestions to improve the WisDuino RAK811 evaluation board's documentation

### ISSUE THREAD

**Issue by kruschk** [RAKWireless/rakwireless-docs#15]
I ran into several minor issues with the [WisDuino RAK811 evaluation board's documentation](https://docs.rakwireless.com/Product-Categories/WisDuino/RAK811-Evaluation-Board/Overview/) that made it quite difficult to configure my endpoint correctly. Implementing the following suggestions might help to improve the documentation:

- When configuring OTAA, the quick-start guide says to use the [“DeviceProfile_OTAA”](https://github.com/RAKWireless/rakwireless-docs/blame/158e94d13b34cf4ce1c0b3052d165e51031a7fef/docs/Product-Categories/WisDuino/RAK811-Evaluation-Board/Quickstart/README.md#L461) device profile in ChirpStack; however, this is not included in ChirpStack by default, and there's no mention of how it should be defined. Steps on how to properly configure the device profile should be included.
- The quick-start guide says [ChirpStack does not require the device to have an application EUI set](https://github.com/RAKWireless/rakwireless-docs/blame/158e94d13b34cf4ce1c0b3052d165e51031a7fef/docs/Product-Categories/WisDuino/RAK811-Evaluation-Board/Quickstart/README.md#L496), so I didn't change mine from the default `0x0000000000000000`. Unfortunately, if this value is not changed, the device will return ERROR 82 when trying to join the network. Once I figured out what this error code meant (see my next point), I was able to work around it by setting the application EUI to a dummy value (e.g. `0x0000000000000001`); I think the documentation could be improved with a note to this effect.
- I couldn't find a listing of the AT command error codes anywhere in the RAK811 evaluation board's documentation. When my endpoint returned ERROR 82, I struggled to find out what that meant until I stumbled upon the [error code table](https://docs.rakwireless.com/Product-Categories/WisDuo/RAK811-Breakout-Board/AT-Command-Manual/#error-code-table) in the [RAK811 breakout board's AT command manual](https://docs.rakwireless.com/Product-Categories/WisDuo/RAK811-Breakout-Board/AT-Command-Manual/). In my opinion, it would be better to include a link to that manual rather than the [incomplete summary that's currently in the evaluation board's documentation](https://github.com/RAKWireless/rakwireless-docs/blame/158e94d13b34cf4ce1c0b3052d165e51031a7fef/docs/Product-Categories/WisDuino/RAK811-Evaluation-Board/Quickstart/README.md#L675).
-  Steps describing how to correctly configure the LoRa channels in the quick-start guide would be helpful. My working assumption is that the channels used by the endpoint should match those used by the gateway.

**Comment by MarkNambatac** [comment]
Issue fixed in commit: 8e56951da0dc3d14492a383882db9865faef00c2
