### ISSUE TITLE
About pdf document

### ISSUE THREAD

**Issue by Microhawk** [RAKWireless/rakwireless-docs#28]
Hi everyone,
I saw your website recently and it feels pretty good. I have a question about pdf documents.
Can you give me some tips on how to achieve this effect.
I have tried many methods recently without success.
Looking forward to your reply.
![image](https://user-images.githubusercontent.com/33093124/122208782-5340a200-ced6-11eb-93c2-422df140d792.png)

**Comment by Microhawk** [comment]
@MarkNambatac 
If you have time, could you answer it for me? I'm looking forward to your reply.

**Comment by MarkNambatac** [comment]
Hi @Microhawk , thank you for your interest in our Documentation Center. Unfortunately, I can't answer that for you as this is not a documentation-related issue. We wish you all the best in your personal project! Stay safe 👍
