### ISSUE TITLE
Documentation on configuring mqtt broker on the gateway

### ISSUE THREAD

**Issue by balakathiresh-impiger** [RAKWireless/rakwireless-docs#30]
Hi 
First things first. Your documentation on how to integrate with AWS IoT server is fantastic.
Since you started supporting mqtt in the gateway products, can you please publish some documentation on how to integrate with mqtt brokers.

**Comment by MarkNambatac** [comment]
Hi @balakathiresh-impiger , thank you for the feedback regarding our AWS IoT Server Guide. At the moment, our team is still working on that 👍
