### ISSUE TITLE
Measurement for the outdoor case 

### ISSUE THREAD

**Issue by spot88** [RAKWireless/rakwireless-docs#39]
Hi! Can't find anywhere the dimensjons on the outdoor case, can you upload this or tell me.

**Comment by spot88** [comment]
Bobcat miner 300 that is.

**Comment by MarkNambatac** [comment]
Hi @spot88 , thanks for submitting an issue in our Documentation Center. For the Outdoor Case, attached below are the correct dimensions. We will include this in our docs as well. Thanks! 
![Image Pasted at 2021-8-27 18-10](https://user-images.githubusercontent.com/19337729/131296531-aa251444-df94-42a0-8dcf-8ed7a24cfbdc.png)

**Comment by MarkNambatac** [comment]
Issue Solved at 22042255dbe3b145a4a02fb97e5d2e129c120bda
