### ISSUE TITLE
interval parameter is wrong

### ISSUE THREAD

**Issue by HutchinsonBSS** [RAKWireless/rakwireless-docs#4]
For RAK 7200

Current parameter: at+set_config=lora:send_interval:X
Good paramenter:at+set_config=lora:send_interval:X:Y 

Set a certain channel on or off.
• X - the channel number, and you can check which channel can be set before you set it.
• Y - 0: off, 1: on

**Comment by MarkNambatac** [comment]
Pull Request already opened in #3
