### ISSUE TITLE
Restore backup of SD card on new bigger SD card

### ISSUE THREAD

**Issue by bogdanpopey** [RAKWireless/rakwireless-docs#52]
Hello,

Can you please share a tutorial on how we could restore the backup on a bigger SD card?

Thank you,
Bogdan

**Comment by MarkNambatac** [comment]
Hi @bogdanpopey , thank you for submitting an issue in our Documentation Center. May I know which product are you referring to?

**Comment by bogdanpopey** [comment]
https://docs.rakwireless.com/Product-Categories/WisGate/RAK-Hotspot-Miner/Backup/
Rak V2 miner.

**Comment by jmarcelino** [comment]
> https://docs.rakwireless.com/Product-Categories/WisGate/RAK-Hotspot-Miner/Backup/
> Rak V2 miner.

You don't need to backup the V2 miner SD card you can just flash a new image, all V2 and MNTD miners run the same image. This is also the only way to make use of additional space on the SD card.

Please contact out support teams on RAKstars or MNTD Gold Discord for the latest firmware link.
