### ISSUE TITLE
RAK3172 Low-Level Development patches ST firmware release

### ISSUE THREAD

**Issue by danak6jq** [RAKWireless/rakwireless-docs#54]
I see the instructions for RAK3172 low-level development start with the STM32WL example code, then copy a handful of files to patch the resulting project.

This means that every time you run Cube to reconfigure peripherals or the LoRa application, the files need to be patched again, because Cube over-writes them.

Also, this means that the project can not be cloned into a new project using Cube 

<img width="403" alt="image" src="https://user-images.githubusercontent.com/942815/149569789-7d5acd7a-95ab-4208-baad-58463d3d1b8c.png">

I did the same thing for the RAK3172-E that I did for the Seeed LoRa-E5 Mini; I created a new STM32CubeIDE project from scratch, configuring it the same as the example code, added BSP file support for the RAK3172 (including real battery level and a bit for the RAK5005 power switch) and then merged in the example code changes in lora_app.c.

This means the project can be re-generated as desired (with the warning that one needs to modify one line of code in lora_app.c to use LocalGetBatteryLevel, this is over-written by Cube), and that new projects can be created as desired using the 'new project from existing IOC' feature.

This is still the LoRaWAN End Node Client example from ST with a few changes for my own hardware, but represents a good starting point for application development when cloned.

Initial testing has proven good so far; I invite the experts at RAK to review my BSP file changes, and I also ask you to consider referencing the still-new repo in your documentation for low-level development.

Repo:

https://github.com/danak6jq/RAK3172

**Comment by carlrakwireless** [comment]
Hi,

Thank you for your awesome contribution. I'll review/check it out and update our Low Level Development guide as necessary 👍🏽

**Comment by carlrakwireless** [comment]
Hi @danak6jq ,

I initially can't run your code because it was built on CubeIDE v1.8.0. I just updated mine directly from the IDE without reinstalling then all is ok 👍🏽 

Then I got issue on `Release` build configuration since the BSP directory is not included in the Path.  I have to I've added it manually so now I can compile it with no errors. I am not sure why I there is no uplink from my device. Already tested in 2 RAK3172. I am pretty sure on the EUI and KEYS. LoRaWAN version of the network server is 1.0.3. I only change CLASS C to CLASS A and nothing else. Do I forget something? You have some sensors in your code but I am not really sure what are those. Any insights you might have is greatly appreciated. Thanks again on your great work 🙂

**Comment by danak6jq** [comment]
I should do a README about the BSP path. Which region are you testing with? For US915, I didn't select hybrid, so the first Join attempt is missed if the gateway is configured to sub-band 2. 6 seconds later there's a retry and it joins sub-band 2. For other than US915, I don't think there's a sub-band issue, fewer than 8 channels.

Also - I found issues with the default compiler optimization of -O0; go into project settings -> GCC Optimization and select -Og or -O3.

Have you tried plugging a USB cable in to watch the log messages? Paste them here if you can.

**Comment by danak6jq** [comment]
There should be no issue with changing to Class A

**Comment by danak6jq** [comment]
Also, when you're attempting to join, have a look at the live LoRaWAN frames on the gateway if you can, see if there's an unaswered Join Request

**Comment by carlrakwireless** [comment]
I will uninstall the old 1.7.0 STM32CubeIDE version to test it again with freshly installed STM32CubeIDE v1.8.0. It is really suspicious that I don't see any serial logs and any packets received by the Gateway. Thank you for the reply and I'll update you for any progress.

**Comment by danak6jq** [comment]
Do you have an ST-Link? How are you programming the MCU - with the embedded bootloader or ST-Link?

**Comment by carlrakwireless** [comment]
Yes I have STLink. I can do it via debug. But on my initial test, I am using a USB-UART via STM32CubeProgrammer since not all users have STLink and using the UART Bootloader is more accessible to most users.

**Comment by danak6jq** [comment]
Why don't you try programming with ST-Link since that's what I've been using, and I'll try the serial bootloader (USB-Serial + CubeProgrammer)

**Comment by carlrakwireless** [comment]
Hi @danak6jq ,

Uploading it via STLINK V2 worked :)

**Comment by danak6jq** [comment]
@carlrakwireless not surprisingly, uploading via the serial bootloader over the USB port (jumpering BOOT0 manually), results in a non-responsive MCU. I'm going to make a simple LED flasher program and try uploading that, or maybe verify/download the flash programmed with ST-Link using the bootloader (it should match)

**Comment by danak6jq** [comment]
This appears to be an STM32CubeProgrammer issue.

I've updated the repo with a change to default to -Og optimize for debug; I saw some issues with -O0. Also added AS923 and deleted an extra blank line in sys_app.c

I suggest pulling the repo again to get the optimization change.

**Comment by danak6jq** [comment]
I've commented at the ST Community forum asking about issues with STM32CubeProgrammer and UART programming, this really seems to be an issue with either STM32CubeProgrammer or the STM32WLE5 embedded bootloader (will check the errata)

**Comment by danak6jq** [comment]
@carlrakwireless I experimented a bit these evening with UART / bootloader, and found that, after a failed download attempt (programming) where the last sector of the binary is not programmed, using "erase sector" to just erase the last sector would allow the next programming attempt to succeed. I think this might be an instance of erratum 2.2.2 "Overwriting with all zeros a Flash memory location previously programmed with all ones fails" - but I am not sure why the sector erase would address that.

Anyway, I think you can successfully program with UART/CubeProgrammer if you try this.

**Comment by danak6jq** [comment]
@carlrakwireless just to summarize - and I think this might apply to any firmware programmed using the UART/embedded bootloader - there's a verify error after attempting the download in CubeProgrammer, it occurs on a sector boundary. Using CubeProgrammer to erase just that sector, or possibly that sector and the ones before/after it, allow the next program/verify to succeed.

I have no reason to believe it is specific to this repo.

**Comment by danak6jq** [comment]
@carlrakwireless Thanks for looking into this.

I had a look at RUI on RAK811 some time ago, was impressed. I am, however, deeply concerned about issues I've encountered in the RAK-maintain LoRaWAN stack on the RAK4630. Any idea if the RAK3172 version of RUI uses the ST-supplied firmware for the LoRaWAN stack?

Of course, I also appreciate the flexibility that I can relatively easily swap another STM32WLE5 module with minor firmware changes depending on market conditions - and I expect RUI wouldn't have that flexibility.

**Comment by TolbyT** [comment]
@danak6jq @carlrakwireless May I check which part of the code should I edit if I need to interface to my external sensor?

And do I need to make any changes to the .ioc peripherals if I need to connect via UART to my external sensor?
