### ISSUE TITLE
RAK7258

### ISSUE THREAD

**Issue by Devansh-Shah-5400** [RAKWireless/rakwireless-docs#78]
I tried to update my firmware for RAK7258 and after that i am unable to access my gateway via WiFi as it is not showing up in available list

**Comment by manolovm** [comment]
Thee firmware update sometimes might fail during the process. We are trying to find the root problem that causes this issue. The solution is to the an OpenWRT recovery procedure
1. For Windows: https://docs.rakwireless.com/Knowledge-Hub/Learn/OpenWRT-Recovery-Procedure/
2. For Mac: https://docs.rakwireless.com/Knowledge-Hub/Learn/WisGateOS-Recovery-Procedure-for-MacOS/

**Comment by Devansh-Shah-5400** [comment]
Hey @manolovm, I tried the OpenWRT procedure with a console cable but I am not getting the screen on the PuTTY, its just a blank black screen.
